shopproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('supplies.urls')),
]

supplies/urls.py
from django.urls import path, include
from . import views 


urlpatterns = [
    path('', views.indexView, name='index'),
    path('detail/<int:pk>/', views.detailView, name='detail'),
    path('edit/<int:pk>/', views.editView, name='edit'),
    path('insumo/', views.insumoView, name='insumo'),
    path('borrar/<int:pk>/', views.deleteView, name='borrar'),
    path('pedidos/', views.pedidosIndexView, name="pedidos"),
    path('pedidos/detalle/<int:pk>/', views.pedidoDetailView, name="pedidoDetalle"),
]

supplies/models.py
from django.db import models


class Sucursal(models.Model):
    nombre = models.CharField(max_length=120)

    def __str__(self):
        return self.nombre


class Articulo(models.Model):
    nombre = models.CharField(max_length=120, help_text='Nombre o descripción')
    descripcion = models.TextField()
    precio = models.FloatField(default=0.0)

    def __str__(self):
        return self.nombre


class Inventario(models.Model):
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE)
    articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)

    def __str__(self):
        return str(self.sucursal) + " - " + str(self.articulo)

supplies/forms.py
from django import forms
from .models import Sucursal, Articulo, Inventario

class SucursalForm(forms.ModelForm):
    class Meta:
        model = Sucursal
        fields = "__all__"


class ArticuloForm(forms.ModelForm):
    class Meta:
        model = Articulo
        fields = "__all__"


class InventarioForm(forms.ModelForm):
    class Meta:
        model = Inventario
        fields = "__all__"

supplies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SucursalForm, ArticuloForm, InventarioForm
from .models import Sucursal, Articulo, Inventario
from django.views.generic import ListView, DetailView, TemplateView
from django.http import HttpResponse
import requests, json, sys



# SUPPLIES #

def indexView(request):
	r = requests.get('http://localhost:8000/api/')
	if r.status_code == 200:
		insumos = r.json()

	return render(request, "supplies/index.html", {"insumos": insumos})


def detailView(request, pk):
	r = requests.get('http://localhost:8000/api/detalle/' + str(pk))
	if r.status_code == 200:
		insumos = r.json()
	return render(request, "supplies/post-detail.html", {"insumo": insumos})



def insumoView(request):
	if request.method == 'POST':
		form = ArticuloForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('index')
	form = ArticuloForm()
	return render(request,'supplies/post.html',{'form': form}) 


def editView(request, pk, template_name='edit.html'):
    r = requests.get('http://localhost:8000/api/detalle/' + str(pk))
    (pk)
    if r.status_code == 200:
        insumos = r.json()
    return render(request, "supplies/edit.html", {"insumo": insumos})
    #form = ArticuloForm(request.POST or None, instance=post)
    #if form.is_valid():
    #    form.save()
    #    return redirect('index')
    #return render(request, template_name, {'form':form})


def deleteView(request, pk, template_name='confirm_delete.html'):
    r = requests.get('http://localhost:8000/api/detalle/' + str(pk))
    (pk)
    if r.status_code == 200:
        insumos = r.json()
    return render(request, "supplies/confirm_delete.html", {"insumo": insumos})


# INVOICES #

def pedidosIndexView(request):
	r = requests.get('http://localhost:8000/api/pedidos/')

	if r.status_code == 200:
		pedido = r.json()
	pedido_str = json.dumps(pedido)
	pedido_arr = json.loads(pedido_str)
	
	r2 = requests.get('http://localhost:8000/api/sucursales/detalle/' + str(pedido_arr[0]['sucursal']))
	r3 = requests.get('http://localhost:8000/api/detalle/' + str(pedido_arr[0]['insumo']))

	if r2.status_code == 200:
		sucursal = r2.json()
	
	if r3.status_code == 200:
		insumo = r3.json()

	return render(request, "pedidos/index.html", { "pedidos": pedido, "sucursales":  sucursal, "insumos": insumo })


def pedidoDetailView(request, pk):
	r = requests.get('http://localhost:8000/api/pedidos/detalle/' + str(pk))
	if r.status_code == 200:
		pedidos = r.json()
	return render(request, "pedidos/post-detail.html", {"pedido": pedidos})

shopproject/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Shop Project</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body>

{% block content %}



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</body>
{% endblock %}
</html>

shopproject/templates/pedidos/index.html
{% extends '../base.html' %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
			<div  class="col-md-10 col-xs-10 col-sm-10">
				<h3 class="round3" style="text-align:center;">Listado de Art&iacute;culos</h3>
		</div>
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
	</div>
	<div class="row">
		<div class="col-md-10 col-xs-10 col-sm-10"></div>
		<div class="col-md-2 col-xs-1 col-sm-1">
			<br/>
            <a href="{% url 'insumo' %}">
              <button type="button" class="btn btn-success">
                Nuevo <span class="glyphicon glyphicon-plus"></span>
              </button>
            </a>
		</div>
	</div>
	<br/>
	{% for pedido in pedidos %}
		<div class="row"> 
			<div class="col-md-1 col-xs-1 col-sm-1"></div> 
			<div class="col-md-7 col-xs-7 col-sm-7">
				<ul class="list-group">
					
			    <li class="list-group-item ">
					<a href="{% url 'pedidoDetalle' pedido.id %}">{{ pedido.id }} - {{ sucursales.nombre }} - {{ insumos.nombre }}</a>  <span class="badge"></span>
				</li>	
			  </ul>
				<br>
			</div>
			
		</div>
	{% endfor %}
</div>
{% endblock %}

shopproject/templates/pedidos/post-detail.html
{% extends '../base.html' %}
{% block content %}
<div class="container-fluid">
<div class="row"></div>
<br/>
<div class="row">
	<div class="col-md-1 col-xs-1 col-sm-1">
    </div>
	<div class="col-md-8 col-xs-8 col-sm-8">
		<p class="h2">
			{{pedido.sucursal}}
		</p>
    </div>
	<div class="col-md-1 col-xs-1 col-sm-1">
		<a href="{% url 'edit' pedido.id %}">
			<button type="button" class="btn btn-info">
				<span class="glyphicon glyphicon-pencil"></span>
			</button>
		</a>
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1">
		<a href="{% url 'borrar' pedido.id %}">
			<button type="button" class="btn btn-danger">
				<span class="glyphicon glyphicon-trash"></span>
			</button>
		</a>
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
<div class="row">
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
	<div class="col-md-10 col-xs-10 col-sm-10">
	{{pedido.insumo}}
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
</div>
{% endblock %}

shopproject/templates/supplies/confirm_delete.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html>
	<head>
		<title>Shop Project</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	</head>
	<body>
		<div class="container">
		<br>
			<div class="row">
				<div class="col-md-2 col-xs-2 col-sm-2"></div>
						<form method="post" id="deleteForm" onsubmit='return onSubmit(this)'>
							{% csrf_token %}
						<div class="form-row">
						<input type="hidden" id="pk" value="{{ insumo.id }}"/>
							<div class="alert alert-danger">
								¿Est&aacute;s seguro que deseas borrar {{ insumo.nombre }}?
								<button type="submit" class="btn btn-danger" style="margin-left: 15px;">
									<span class="glyphicon glyphicon-trash"></span>
								</button>
							</div>
						</div>
						
						</form>
						<a href="{% url 'index' %}" type="submit" id="submit" class="btn btn-success">Cancelar</a>
				</div>
			</div>
		</div>


		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<script>
			function onSubmit( form ){

				var pk = document.getElementById("pk").value;

				var insumo = {
					"pk": pk,
				}

				$.ajax({
					type: "POST",
					url: "http://localhost:8000/api/borrar/" + pk + "/",
					data: JSON.stringify(insumo),
					contentType: "application/json; charset=utf-8",
					crossDomain: true,
					dataType: "json",
					success: function (data, status, jqXHR) {
						window.location.replace("http://localhost:8080/");
					},

					error: function (jqXHR, status) {
						// error handler
						console.log(jqXHR);
						alert('fail' + status.code + "<br>" + "http://localhost:8000/api/borrar/" + pk + "/");
					}
				});
			}

		</script>	
	</body>
</html>

shopproject/templates/supplies/edit.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html>
	<head>
		<title>Shop Project</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-1 col-xs-1 col-sm-1"></div>
				<div  class="col-md-10 col-xs-10 col-sm-10 ">
				<br/>
					<h6 style="text-align:center;"><font color="red"> Todos los campos son obligatorios</font> </h6>
				</div>
				<div class="col-md-1 col-xs-1 col-sm-1">
				</div>
			</div>
			<div class="row">
				<div class="col-md-1 col-xs-1 col-sm-1"></div>
				<div class="col-md-10 col-xs-10 col-sm-10">
					
					<form method="post" id="editForm" onsubmit='return onSubmit(this)'>
						{% csrf_token %}
						<div class="form-group">
							<label for="id_pk">Clave:</label>
							<input type="text" name="id_pk" value="{{ insumo.id }}"class="form-control" required="" id="id_pk" disabled>
						</div>
						<div class="form-group">
							<label for="id_nombre">Nombre:</label>
							<input type="text" name="nombre" value="{{ insumo.nombre }}" maxlength="120" class="form-control" required="" id="id_nombre">
						</div>
						
						<div class="form-group">
							<label for="id_descripcion">Descripcion:</label>
							<textarea name="descripcion" cols="40" rows="10" class="form-control" required="" id="id_descripcion">{{ insumo.descripcion }}</textarea>
						</div>
						
						<div class="form-group">
							<label for="id_precio">Precio:</label>
							<input type="number" name="precio" value="{{ insumo.precio }}" step="any" class="form-control" required="" id="id_precio">
						</div>
						<button type="submit" id="submit" class="btn btn-success">Guardar</button>
						<a href="{% url 'index' %}" type="submit" id="submit" class="btn btn-danger">Cancelar</a>
					</form>
				<br>
				</div>
				<div class="col-md-1 col-xs-1 col-sm-1"></div>
			</div>
		</div>



		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


		<script>
			function onSubmit( form ){

				var pk = document.getElementById("id_pk").value;
				var nombre = document.getElementById("id_nombre").value;
				var descripcion = document.getElementById("id_descripcion").value;
				var precio = document.getElementById("id_precio").value;

				var insumo = {
					"pk": pk,
					"nombre": nombre,
					"descripcion": descripcion,
					"precio": precio,
				}

				$.ajax({
					type: "POST",
					url: "http://localhost:8000/api/editar/" + pk + "/",
					data: JSON.stringify(insumo),
					contentType: "application/json; charset=utf-8",
					crossDomain: true,
					dataType: "json",
					success: function (data, status, jqXHR) {
						window.location.replace("http://localhost:8080/edit/" + pk + "/");
					},

					error: function (jqXHR, status) {
						// error handler
						console.log(jqXHR);
						alert('fail' + status.code + "<br>" + url);
					}
				});
			}
		</script>
	</body>
</html>

shopproject/templates/supplies/index.html
{% extends '../base.html' %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
			<div  class="col-md-10 col-xs-10 col-sm-10">
				<h3 class="round3" style="text-align:center;">Listado de Art&iacute;culos</h3>
		</div>
		<div class="col-md-1 col-xs-1 col-sm-1"></div>
	</div>
	<div class="row">
		<div class="col-md-10 col-xs-10 col-sm-10"></div>
		<div class="col-md-2 col-xs-1 col-sm-1">
			<br/>
            <a href="{% url 'insumo' %}">
              <button type="button" class="btn btn-success">
                Nuevo <span class="glyphicon glyphicon-plus"></span>
              </button>
            </a>
		</div>
	</div>
	<br/>
	{% for insumo in insumos %}
		<div class="row"> 
			<div class="col-md-1 col-xs-1 col-sm-1"></div> 
			<div class="col-md-7 col-xs-7 col-sm-7">
				<ul class="list-group">
					
			    <li class="list-group-item ">
					<a href="{% url 'detail' insumo.id %}">{{ insumo.nombre }}</a>  <span class="badge"></span>
				</li>	
			  </ul>
				<br>
			</div>
			<div class="col-md-1 col-xs-1 col-sm-1">
				<a href="{% url 'detail' insumo.id %}">
					<button type="button" class="btn btn-info">
						<span class="glyphicon glyphicon-open"></span>
					</button>
				</a>
			</div>
			<div class="col-md-1">
				<a href="{% url 'edit' insumo.id %}">
					<button type="button" class="btn btn-info">
						<span class="glyphicon glyphicon-pencil"></span>
					</button>
				</a>
			</div>
			<div class="col-md-1">
				<a href="{% url 'borrar' insumo.id %}">
					<button type="button" class="btn btn-danger">
						<span class="glyphicon glyphicon-trash"></span>
					</button>
				</a>
			</div>
			<div class="col-md-1 col-xs-1 col-sm-1"></div>
		</div>
	{% endfor %}
</div>
{% endblock %}

shopproject/templates/supplies/post-detail.html
{% extends '../base.html' %}
{% block content %}
<div class="container-fluid">
<div class="row"></div>
<br/>
<div class="row">
	<div class="col-md-1 col-xs-1 col-sm-1">
    </div>
	<div class="col-md-8 col-xs-8 col-sm-8">
		<p class="h2">
			{{insumo.nombre}}
		</p>
    </div>
	<div class="col-md-1 col-xs-1 col-sm-1">
		<a href="{% url 'edit' insumo.id %}">
			<button type="button" class="btn btn-info">
				<span class="glyphicon glyphicon-pencil"></span>
			</button>
		</a>
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1">
		<a href="{% url 'borrar' insumo.id %}">
			<button type="button" class="btn btn-danger">
				<span class="glyphicon glyphicon-trash"></span>
			</button>
		</a>
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
<div class="row">
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
	<div class="col-md-10 col-xs-10 col-sm-10">
	{{insumo.descripcion}}
	</div>
	<div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
</div>
{% endblock %}

shopproject/templates/supplies/post.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
	<head>
		<title>Posts</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<style type="text/css">
		</style>
			
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-1 col-xs-1 col-sm-1"></div>
			
				<div  class="col-md-10 col-xs-10 col-sm-10 ">
				<br/>
					<h6 style="text-align:center;"><font color="red"> Todos los campos son obligatorios </font> </h6>
				</div>
				<div class="col-md-1 col-xs-1 col-sm-1">
				</div>
			</div>
			<div class="row">
				<div class="col-md-1 col-xs-1 col-sm-1"></div>
				<div class="col-md-10 col-xs-10 col-sm-10">
					<form method="post" id="createForm" onsubmit='return onSubmit(this)'>
						{% csrf_token %}
						<div class="form-group">
							<label for="id_nombre">Nombre:</label>
							<input type="text" name="nombre" value="" maxlength="120" class="form-control" required="" id="id_nombre">
						</div>
						
						<div class="form-group">
							<label for="id_descripcion">Descripcion:</label>
							<textarea name="descripcion" cols="40" rows="10" class="form-control" required="" id="id_descripcion"></textarea>
						</div>
						
						<div class="form-group">
							<label for="id_precio">Precio:</label>
							<input type="number" name="precio" value="" step="any" class="form-control" required="" id="id_precio">
						</div>
						<button type="submit" id="submit" class="btn btn-success">Guardar</button>
						<a href="{% url 'index' %}" type="submit" id="submit" class="btn btn-danger">Cancelar</a>
					</form>
					<br>
				</div>
				<div class="col-md-1 col-xs-1 col-sm-1"></div>
			</div>
		</div>


		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<script>
			function onSubmit( form ){

				var nombre = document.getElementById("id_nombre").value;
				var descripcion = document.getElementById("id_descripcion").value;
				var precio = document.getElementById("id_precio").value;

				var insumo = {
					"nombre": nombre,
					"descripcion": descripcion,
					"precio": precio,
				}

				$.ajax({
					type: "POST",
					url: "http://localhost:8000/api/crear/",
					data: JSON.stringify(insumo),
					contentType: "application/json; charset=utf-8",
					crossDomain: true,
					dataType: "json",
					success: function (data, status, jqXHR) {
						window.location.replace("http://localhost:8080/");
					},

					error: function (jqXHR, status) {
						// error handler
						console.log(jqXHR);
						alert('fail' + status.code + "<br>" + url);
					}
				});
			}

		</script>	
	</body>
</html>